version: 0.0
os: linux
files:
  - source: .
    destination: /tmp/github
hooks:
  ApplicationStop:
    - location: deployment/application-stop.sh
      timeout: 300
  ApplicationStart:
    - location: deployment/application-start.sh
      timeout: 300